version: '3.8'

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge

services:

  school-back:
    build:
      context: ./
      dockerfile: Dockerfile
    image: school:latest
    ports:
      - "8080:8080"
    networks:
       - app-network
    environment:
      - MYSQL_DATABASE_NAME=demo_application_schema
      - MYSQL_DATABASE_URL=jdbc:postgres://postgres/demo_application_schema
    volumes:
      - ./:/app


  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=springuser
      - POSTGRES_PASSWORD=SpringUserPassword12
    networks:
      - app-network
